Repository nv-morpheus/morpheus-experimental, pull requests merged in 2024-10, with the labels that each got.

#85 Placeholder for fraud workflow
  ai-credit-fraud-workflow/README.md
Labels: doc, non-breaking

#88 Update copyright heaers
  ai-credit-fraud-workflow/README.md
  anomalous-auth-detection/README.md
  dga-detection/README.md
  gnn-asset-clustering/README.md
  ids-detection/README.md
  log-sequence-ad/README.md
Labels: improvement, non-breaking

#89 Fix various linting and formatting errors
  cyber-foundation/training-inference/prepare-prefix.py
  cyber-foundation/training-inference/train-prefix.py
Labels: bug, non-breaking

#90 Credit fraud workflow
  ai-credit-fraud-workflow/Dockerfile
  ai-credit-fraud-workflow/LICENSE
  ai-credit-fraud-workflow/README.md
  ai-credit-fraud-workflow/conda/fraud_conda_env.yaml
  ai-credit-fraud-workflow/data/Sparkov/README.md
  ai-credit-fraud-workflow/data/Sparkov/raw/READEME.md
  ai-credit-fraud-workflow/data/TabFormer/README.md
  ai-credit-fraud-workflow/data/TabFormer/raw/README.md
  ai-credit-fraud-workflow/docs/background.md
  ai-credit-fraud-workflow/docs/datasets.md
  ai-credit-fraud-workflow/docs/run_notebooks.md
  ai-credit-fraud-workflow/docs/setup.md
  ai-credit-fraud-workflow/docs/workflow.md
  ai-credit-fraud-workflow/img/3-partite.jpg
  ai-credit-fraud-workflow/img/High-Level.jpg
  ai-credit-fraud-workflow/img/Model-Building.png
  ai-credit-fraud-workflow/img/Splash.jpg
  ai-credit-fraud-workflow/img/this-workflow.jpg
  ai-credit-fraud-workflow/notebooks/inference_gnn_based_xgboost_TabFormer.ipynb
  ai-credit-fraud-workflow/notebooks/inference_xgboost_Sparkov.ipynb
  ai-credit-fraud-workflow/notebooks/inference_xgboost_TabFormer.ipynb
  ai-credit-fraud-workflow/notebooks/preprocess_Sparkov.ipynb
  ai-credit-fraud-workflow/notebooks/preprocess_Tabformer.ipynb
  ai-credit-fraud-workflow/notebooks/train_gnn_based_xgboost.ipynb
  ai-credit-fraud-workflow/notebooks/train_xgboost.ipynb
  ai-credit-fraud-workflow/requirements.txt
Labels: feature request, non-breaking

#91 Back-port of Credit fraud workflow to 24.10
  ai-credit-fraud-workflow/Dockerfile
  ai-credit-fraud-workflow/LICENSE
  ai-credit-fraud-workflow/README.md
  ai-credit-fraud-workflow/conda/fraud_conda_env.yaml
  ai-credit-fraud-workflow/data/Sparkov/README.md
  ai-credit-fraud-workflow/data/Sparkov/raw/READEME.md
  ai-credit-fraud-workflow/data/TabFormer/README.md
  ai-credit-fraud-workflow/data/TabFormer/raw/README.md
  ai-credit-fraud-workflow/docs/background.md
  ai-credit-fraud-workflow/docs/datasets.md
  ai-credit-fraud-workflow/docs/run_notebooks.md
  ai-credit-fraud-workflow/docs/setup.md
  ai-credit-fraud-workflow/docs/workflow.md
  ai-credit-fraud-workflow/img/3-partite.jpg
  ai-credit-fraud-workflow/img/High-Level.jpg
  ai-credit-fraud-workflow/img/Model-Building.png
  ai-credit-fraud-workflow/img/Splash.jpg
  ai-credit-fraud-workflow/img/this-workflow.jpg
  ai-credit-fraud-workflow/notebooks/inference_gnn_based_xgboost_TabFormer.ipynb
  ai-credit-fraud-workflow/notebooks/inference_xgboost_Sparkov.ipynb
  ai-credit-fraud-workflow/notebooks/inference_xgboost_TabFormer.ipynb
  ai-credit-fraud-workflow/notebooks/preprocess_Sparkov.ipynb
  ai-credit-fraud-workflow/notebooks/preprocess_Tabformer.ipynb
  ai-credit-fraud-workflow/notebooks/train_gnn_based_xgboost.ipynb
  ai-credit-fraud-workflow/notebooks/train_xgboost.ipynb
  ai-credit-fraud-workflow/requirements.txt
Labels: feature request, non-breaking
